### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by avatar-lavventura** [vutran/yahoo-stocks#6]
```
❯ node test.js
(node:87472) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/alper/doo/test.js:1
import { lookup, history } from 'yahoo-stocks';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

```

**Comment by joey2031** [comment]
I got the api to work with this code:

```

var stockAPI = require('yahoo-stocks');

stockAPI.lookup('AAPL').then(response => {
    console.log(response);
});

```
However it seems like the lookup function is broken (look at the other issue I made) but the history function still works:

<img width="440" alt="image" src="https://user-images.githubusercontent.com/36198917/211101613-7394aa51-835a-438f-9f45-769817ce518d.png">
